#!/bin/bash

domain=$1
subdomain=$2

if [[ -z $domain ]]; then
  echo "Error: Missing domain argument."
  exit 1
fi

if [[ -z $subdomain ]]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=($subdomain)
fi

for sub in "${subdomains[@]}"; do
  record=$(dig +short $sub.$domain)
  if [[ -z $record ]]; then
    echo "The subdomain $sub is not found."
  else
    record_type=$(dig +short $sub.$domain | awk '{print $4}')
    destination=$(dig +short $sub.$domain | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination."
  fi
done
