#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Determine server's active IPv4 IPs
ips=($(hostname -I | awk '{print $1}'))

# Create Nginx configuration file for each IP
for ip in "${ips[@]}"
do
  cat <<EOF | sudo tee /etc/nginx/sites-available/$ip.conf > /dev/null
server {
  listen $ip:80;
  server_name _;

  location / {
    root /var/www/html;
    index index.html;
  }
}
EOF
done

# Enable Nginx configuration files
for ip in "${ips[@]}"
do
  sudo ln -s /etc/nginx/sites-available/$ip.conf /etc/nginx/sites-enabled/
done

# Restart Nginx
sudo systemctl restart nginx
